"""Remove accounts left behind by the db test suite.

Why this exists
---------------
delete_all_user_data deliberately never touches the `users` row: erasing what
the system learned about someone and deleting their account are different
requests (see app/services/data_privacy.py). Every db test that registered an
account therefore leaked one, and nobody noticed until a census found 919
accounts, 907 of them generated by the suite since August.

tests/conftest.py now sweeps each run's own accounts, so this only exists for
the backlog that accumulated before that. Run it once and it should stay at
zero; if it keeps finding rows, a test is registering under a prefix the sweep
does not know about, and the fix belongs in _TEST_ACCOUNT_PREFIXES rather than
here.

Safety
------
Dry run by default — it prints what it would delete and changes nothing.
Deletion requires --apply, and is restricted three ways: the name must match
`<known test prefix>_<8 hex>`, the account must hold no events, and anything
outside that shape is reported rather than removed.

    python cleanup_test_accounts.py            # show what would go
    python cleanup_test_accounts.py --apply    # actually delete
"""
import argparse
import asyncio
import os
import re
import sys
from collections import Counter

import asyncpg

# Kept in step with tests/conftest.py. A prefix listed there and missing here
# just means this script reports those rows instead of removing them.
PREFIXES = (
    "alice", "bob", "attacker", "unrelated", "owner", "pytest",
    "orgowner", "orgmember", "orgmember2", "orguser",
    "llmuser", "reproc", "researchuser", "snaphist", "import",
    "warntest", "warntest2", "erase",
)
GENERATED = re.compile(r"^(?:" + "|".join(PREFIXES) + r")_[0-9a-f]{8}$")


def _dsn() -> str:
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        env = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")
        if os.path.exists(env):
            with open(env, encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if line.startswith("DATABASE_URL="):
                        dsn = line.split("=", 1)[1].strip()
                        break
    if not dsn:
        sys.exit("DATABASE_URL is not set and no .env was found.")
    return dsn


async def main(apply: bool) -> None:
    conn = await asyncpg.connect(_dsn())
    try:
        rows = await conn.fetch("SELECT username FROM users")
        names = [r["username"] for r in rows]
        matched = sorted(n for n in names if GENERATED.match(n))
        other = sorted(set(names) - set(matched))

        print(f"accounts total:            {len(names)}")
        print(f"test-shaped (removable):   {len(matched)}")
        print(f"everything else (kept):    {len(other)}")

        by_prefix = Counter(n.rsplit("_", 1)[0] for n in matched)
        for prefix, count in by_prefix.most_common():
            print(f"  {count:5}  {prefix}_<8hex>")

        print("\nkept (not matching a known test prefix):")
        for name in other:
            print(f"        {name}")

        if not matched:
            print("\nNothing to do.")
            return

        # A test account holding events is unexpected; skip it and say so
        # rather than deleting data that might not be test data.
        with_events = {
            r["user_id"] for r in await conn.fetch(
                "SELECT DISTINCT user_id FROM events WHERE user_id = ANY($1::text[])",
                matched,
            )
        }
        if with_events:
            print(f"\nskipping {len(with_events)} account(s) that still hold events:")
            for name in sorted(with_events):
                print(f"        {name}")
            matched = [n for n in matched if n not in with_events]

        if not apply:
            print(f"\nDRY RUN — would delete {len(matched)} account(s). Re-run with --apply.")
            return

        deleted = 0
        for name in matched:
            async with conn.transaction():
                await conn.execute(
                    "UPDATE users SET org_id = NULL, org_role = NULL WHERE org_id IN "
                    "(SELECT id FROM organizations WHERE owner_username = $1)", name)
                await conn.execute("DELETE FROM org_invites WHERE created_by = $1", name)
                await conn.execute("DELETE FROM organizations WHERE owner_username = $1", name)
                result = await conn.execute("DELETE FROM users WHERE username = $1", name)
            deleted += int(result.split()[-1]) if result.split()[-1].isdigit() else 0

        print(f"\ndeleted {deleted} account(s).")
        print("remaining:", await conn.fetchval("SELECT COUNT(*) FROM users"))
    finally:
        await conn.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true",
                        help="actually delete (default is a dry run)")
    asyncio.run(main(parser.parse_args().apply))
