import os
import re
import sys
import uuid
from pathlib import Path

import pytest
import pytest_asyncio

sys.path.insert(0, str(Path(__file__).parent.parent))

# Load .env if available
env_path = Path(__file__).parent.parent / ".env"
if env_path.exists():
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        if key not in os.environ:
            os.environ[key] = value


# The suite drives the rate-limited endpoints far harder than a person would,
# and the limiters are process-global — leaving them on would make results
# depend on test order and on how recently the suite last ran. The limiter's
# own behaviour is covered directly in test_rate_limit.py, which enables it
# explicitly.
os.environ.setdefault("RATE_LIMIT_ENABLED", "false")


@pytest_asyncio.fixture(scope="session")
async def db():
    """Live DB pool for tests marked `db`.

    Skips when there is no reachable database, so the suite stays runnable
    without Postgres. It does NOT skip when the database is reachable but the
    schema fails to apply — that is a broken migration, and a broken migration
    must fail loudly.

    Both used to be caught by one `except`, reported as "DATABASE_URL
    unreachable". A migration that could no longer run then turned into 86
    silently skipped tests and an exit code of 0 — the run looked green while
    testing nothing, which is precisely how a migration that breaks startup
    reaches production.
    """
    from app.db import postgres

    # 1. Connectivity: genuinely optional.
    try:
        pool = await postgres.init_pool()
        async with pool.acquire() as conn:
            await conn.fetchval("SELECT 1")
    except Exception as e:
        pytest.skip(f"DATABASE_URL unreachable: {e}")

    # 2. Schema: not optional. Tests hit the ASGI app via ASGITransport, which
    # does not run FastAPI's lifespan (where the real app applies migrations),
    # so they are applied here — and the real app runs exactly this on every
    # startup. If it raises, the deployed service cannot boot cleanly either.
    try:
        await postgres.run_schema()
    except Exception as e:
        pytest.fail(
            f"run_schema() failed against a reachable database: {e} | "
            f"This is a broken migration, not a missing database. The deployed "
            f"app runs run_schema() on startup, so this would break it too."
        )

    yield postgres
    await postgres.close_pool()


@pytest_asyncio.fixture
async def disposable_user_id(db):
    """A throwaway user_id, deleted (all tables) after the test regardless
    of pass/fail — keeps pytest runs from leaving junk rows in the shared
    dev database."""
    user_id = f"pytest_{uuid.uuid4().hex[:8]}"
    yield user_id
    from app.services import data_privacy
    try:
        await data_privacy.delete_all_user_data(user_id)
        await data_privacy.delete_account(user_id)
    except Exception:
        pass


# Prefixes the db suite generates accounts with, as `<prefix>_<8 hex>`.
# Extend this when a new test registers accounts under a new name.
_TEST_ACCOUNT_PREFIXES = (
    "alice", "bob", "attacker", "unrelated", "owner", "pytest",
    "orgowner", "orgmember", "orgmember2", "orguser",
    "llmuser", "reproc", "researchuser", "snaphist", "import",
    "warntest", "warntest2", "erase",
)

_GENERATED_ACCOUNT = re.compile(
    r"^(?:" + "|".join(_TEST_ACCOUNT_PREFIXES) + r")_[0-9a-f]{8}$"
)


@pytest_asyncio.fixture(scope="session", autouse=True)
async def _sweep_registered_accounts():
    """Delete the accounts this run registered.

    delete_all_user_data deliberately leaves the `users` row alone (erasing
    behaviour and deleting an account are different requests — see
    services/data_privacy.py), so every test that registered an account was
    leaking one into the shared database. Nobody noticed until a census found
    919 accounts, 907 of them generated by this suite since August.

    Fixing it per test file would work until the next file forgot, so the
    sweep lives here instead. Three guards keep it away from real accounts:
    the name must match `<known test prefix>_<8 hex>`, it must not have
    existed before the run started, and a failure to delete is ignored rather
    than escalated.
    """
    from app.db import postgres

    async def usernames():
        try:
            rows = await postgres.fetch("SELECT username FROM users")
            return {r["username"] for r in rows}
        except Exception:
            return set()   # no database configured; the suite skips db tests

    before = await usernames()
    yield

    new_accounts = (await usernames()) - before
    if not new_accounts:
        return

    created = {u for u in new_accounts if _GENERATED_ACCOUNT.match(u)}
    from app.services import data_privacy

    swept = 0
    for username in sorted(created):
        try:
            await data_privacy.delete_all_user_data(username)

            # delete_account refuses while the user owns an organization, and
            # rightly so — removing an owner takes the whole workspace with
            # it. That guard blocked test cleanup, because the org tests
            # create both. Safe here only because this org was created by
            # this run, by an account this run registered.
            await postgres.execute(
                "UPDATE users SET org_id = NULL, org_role = NULL WHERE org_id IN "
                "(SELECT id FROM organizations WHERE owner_username = $1)",
                username,
            )
            await postgres.execute(
                "DELETE FROM organizations WHERE owner_username = $1", username
            )
            await postgres.execute("DELETE FROM org_invites WHERE created_by = $1", username)

            result = await data_privacy.delete_account(username)
            swept += 1 if result.get("deleted") else 0
        except Exception:
            pass

    if swept:
        print(f"[conftest] swept {swept} test account(s) registered by this run")

    # Anything this run created that the sweep does not recognise. Printed
    # rather than deleted: an unknown name is exactly the case where guessing
    # is dangerous. Left silent, these are how 907 accounts accumulated.
    unswept = sorted(new_accounts - created)
    if unswept:
        print(
            f"[conftest] WARNING: {len(unswept)} account(s) created by this run were "
            f"NOT swept (name does not match a known test prefix): "
            + ", ".join(unswept[:10])
            + (" ..." if len(unswept) > 10 else "")
            + " | Add the prefix to _TEST_ACCOUNT_PREFIXES in tests/conftest.py."
        )
