import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import GlassCard from '../../components/ui/GlassCard'
import CharacterCreature3D from '../../components/character/CharacterCreature3D'

const FEATURE_GUIDE = [
  {
    path: '/chat', icon: '💬', title: 'Chat',
    body: 'Talk to your cognitive twin directly. Every answer is generated by a real pipeline run over your actual behavior data — click "Why did the AI say this?" under any reply to see the full reasoning trace, or use the follow-up chips to keep a thread going.',
  },
  {
    path: '/character', icon: '🤖', title: 'Character',
    body: 'The live runtime the chat actually talks through — identity snapshot version, self-model beliefs, memory reference counts, and how the reinforcement-learning loop is currently tuning its behavior. Nothing here is a separate mock; it\'s the same object built fresh on every query.',
  },
  {
    path: '/timeline', icon: '🕐', title: 'Timeline',
    body: 'Your digital diary — every watch, like, and save across Instagram and YouTube in one chronological feed, with the real behavior objects and evidence each event contributed to shown inline. Filter by platform, attention depth, or search captions and creators.',
  },
  {
    path: '/diary', icon: '📔', title: 'Diary',
    body: 'A weekly or monthly "story" narrated entirely from real, computed stats over your actual events — no LLM call, just the same deterministic-facts-to-prose pattern used elsewhere in the app. Every sentence (including the comparisons to the previous period) traces back to a real number.',
  },
  {
    path: '/goals', icon: '🎯', title: 'Goals',
    body: 'Set a real intention ("do more of X", "do less of Y") against real topic keywords, and get back an alignment score computed from your actual behavior_objects — their importance and whether they\'re growing or declining — not a number you type in yourself. Re-scored live every time you open the page.',
  },
  {
    path: '/graph', icon: '🕸️', title: 'Knowledge Graph',
    body: 'A living, physics-driven map of your topics and creators — node size is real importance, color shows which platform a topic came from, and lines are real relationships (shared keywords between topics, or a creator who made content in that topic). Click any node for its full stats, or search to fly the camera to it.',
  },
  {
    path: '/identity', icon: '👤', title: 'Identity',
    body: 'The evolving computational model of who you are: confidence, completeness, sub-profiles (attention, exploration, consistency, habits, motivation), and a real version-by-version evolution timeline.',
  },
  {
    path: '/memory', icon: '🧠', title: 'Memory',
    body: 'Reflection memory (periodic summaries), semantic memory (durable inferences), and pattern memory (recurring behavior lifecycle trends) — searchable in one place.',
  },
  {
    path: '/evidence', icon: 'ℹ️', title: 'Evidence',
    body: 'The raw observational proof behind every inference — evidence type, confidence, and weight, all traceable back to source events.',
  },
  {
    path: '/behavior', icon: '📊', title: 'Behavior',
    body: 'Consolidated topics and creators by importance, plus a Filter Bubble Score measuring how concentrated your attention is on a small set of creators.',
  },
  {
    path: '/planning', icon: '🗂️', title: 'Planning',
    body: 'How the cognitive planner decided what to retrieve and how to reason for each query — intent detection, reasoning mode, retrieval plan.',
  },
  {
    path: '/decision', icon: '⚖️', title: 'Decision',
    body: 'The fact-fusion and conflict-resolution stage: facts in vs. facts out, confidence per decision, and how many conflicts were resolved.',
  },
  {
    path: '/learning', icon: '⚡', title: 'Learning',
    body: 'A real online contextual bandit (not a static heuristic) that learns which nudge helps in each behavioral state. Rate a suggestion 👍/👎 to directly teach the policy.',
  },
  {
    path: '/guardian', icon: '🛡️', title: 'Guardian',
    body: 'Explainable wellbeing monitoring — session timing, sensitive-content signal, and a composite risk score with a persistent alert log (the closest honest equivalent to a push notification without external email/webhook delivery configured).',
  },
  {
    path: '/insights', icon: '📤', title: 'Insights Export',
    body: 'The exportable "Algorithmic Identity Profile" for ad agencies, mental-health research, or academic research — every field source-cited, plus a Campaign Resonance Simulator that scores a hypothetical campaign against your real identity (deterministic, no LLM).',
  },
  {
    path: '/pipeline', icon: '🔄', title: 'Pipeline',
    body: 'A live, stage-by-stage trace of exactly what happened on the most recent query or ingest — timing, counts, and success/failure per stage.',
  },
  {
    path: '/analytics', icon: '📈', title: 'Analytics',
    body: 'Trend lines for behavior objects, evidence, inferences, and confidence over time, sourced from real recorded cognitive metrics.',
  },
]

export default function GuidePage() {
  const navigate = useNavigate()
  const [openStep, setOpenStep] = useState(0)

  return (
    <div style={{ maxWidth: 980, margin: '0 auto' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 32 }}>
        <div style={{ width: 72, height: 72, flexShrink: 0, margin: '-10px 0' }}>
          <CharacterCreature3D size={72} variant="beacon" confidence={0.7} showLabels={false} />
        </div>
        <div>
          <h1 className="gradient-text" style={{ fontSize: 32, fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 6 }}>Guide</h1>
          <p style={{ color: 'var(--text-tertiary)', fontSize: 15 }}>What AIMirror is, how to set it up, and how to use it</p>
        </div>
      </div>

      {/* What is this */}
      <GlassCard gradient>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 10 }}>What AIMirror is</h3>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8 }}>
          AIMirror is a <strong>Cognitive Digital Twin</strong> — it builds an explainable, computational
          model of your online behavior from what you actually watch on Instagram and YouTube, then lets
          you talk to, inspect, and export that model. Every number on every page traces back to a real
          event, and the language model is <em>only</em> a verbalization layer — it never reasons or
          decides anything. All the intelligence (topic clustering, inference, identity construction,
          risk scoring, reinforcement learning) is deterministic, rule-based, and auditable.
        </p>
      </GlassCard>

      {/* Setup */}
      <GlassCard gradient style={{ marginTop: 24 }}>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16 }}>Setup</h3>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {[
            {
              title: '1. Backend', body: (
                <>
                  <code>PYTHONPATH="&lt;repo root&gt;:&lt;repo root&gt;/backend" backend/venv/Scripts/python.exe -m uvicorn app.main:app --host 127.0.0.1 --port 8000</code>
                  <p style={{ marginTop: 8 }}>Applies all database migrations automatically on startup and serves the API on port 8000.</p>
                </>
              ),
            },
            {
              title: '2. Dashboard', body: (
                <>
                  <code>cd dashboard && npm run dev</code>
                  <p style={{ marginTop: 8 }}>Runs on port 5173. <code>dashboard/.env</code> should set <code>VITE_API_URL=http://localhost:8000</code>.</p>
                </>
              ),
            },
            {
              title: '3. Browser extension (live tracking)', body: (
                <>
                  <ol style={{ paddingLeft: 18, margin: 0, lineHeight: 1.9 }}>
                    <li>Open <code>chrome://extensions</code> and enable Developer mode</li>
                    <li>Click "Load unpacked" and select the <code>chrome-extension</code> folder</li>
                    <li>Browse <code>instagram.com/reels</code> or <code>youtube.com</code> — both are tracked automatically</li>
                  </ol>
                  <p style={{ marginTop: 8 }}>See the <a href="/import" style={{ color: '#818cf8' }}>Import page</a> for live source-mix stats once you've watched a few things.</p>
                </>
              ),
            },
          ].map((step, i) => (
            <div key={i}>
              <button
                onClick={() => setOpenStep(openStep === i ? -1 : i)}
                style={{
                  width: '100%', textAlign: 'left', padding: '12px 16px', borderRadius: 8,
                  background: 'rgba(148,163,184,0.04)', border: '1px solid var(--border-subtle)',
                  color: 'var(--text-secondary)', fontSize: 14, fontWeight: 600, cursor: 'pointer',
                  display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                }}
              >
                {step.title}
                <span style={{ color: 'var(--text-muted)', fontSize: 12 }}>{openStep === i ? '▲' : '▼'}</span>
              </button>
              {openStep === i && (
                <div style={{
                  padding: 16, fontSize: 13, color: 'var(--text-tertiary)', lineHeight: 1.7,
                  background: 'rgba(0,0,0,0.15)', borderRadius: 8, marginTop: 6,
                  fontFamily: 'var(--font-mono)',
                }}>
                  {step.body}
                </div>
              )}
            </div>
          ))}
        </div>
      </GlassCard>

      {/* Feature guide */}
      <div style={{ marginTop: 24, marginBottom: 16 }}>
        <h3 style={{ fontSize: 18, fontWeight: 600 }}>What each tab does</h3>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>
        {FEATURE_GUIDE.map(f => (
          <GlassCard key={f.path} hover>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10 }}>
              <div style={{ fontSize: 22 }}>{f.icon}</div>
              <h4 style={{ fontSize: 14, fontWeight: 600 }}>{f.title}</h4>
            </div>
            <p style={{ fontSize: 12.5, color: 'var(--text-tertiary)', lineHeight: 1.6, marginBottom: 12 }}>{f.body}</p>
            <button
              onClick={() => navigate(f.path)}
              style={{
                padding: '5px 12px', borderRadius: 6, border: '1px solid var(--border-subtle)',
                background: 'transparent', color: '#818cf8', fontSize: 12, cursor: 'pointer',
              }}
            >
              Open {f.title} →
            </button>
          </GlassCard>
        ))}
      </div>

      <GlassCard gradient style={{ marginTop: 24 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <div>
            <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 6 }}>Want the deeper technical picture?</h3>
            <p style={{ fontSize: 13, color: 'var(--text-tertiary)' }}>Architecture, key concepts, and the explainability philosophy live on the Documentation page.</p>
          </div>
          <button
            onClick={() => navigate('/documentation')}
            style={{
              padding: '8px 16px', borderRadius: 8, border: '1px solid rgba(99,102,241,0.25)',
              background: 'rgba(99,102,241,0.1)', color: '#a5b4fc', fontSize: 13, fontWeight: 600,
              cursor: 'pointer', whiteSpace: 'nowrap',
            }}
          >
            Read Documentation →
          </button>
        </div>
      </GlassCard>
    </div>
  )
}
