import { useMemo, useState } from 'react'
import { api } from '../../api/client'
import { useApi } from '../../hooks/useApi'
import GlassCard from '../../components/ui/GlassCard'
import Badge from '../../components/ui/Badge'
import StatCard from '../../components/ui/StatCard'
import Reveal from '../../components/motion/Reveal'
import CountUp from '../../components/motion/CountUp'
import { DownloadIcon, CopyIcon, CheckIcon, TargetIcon, LayersIcon, BrainIcon, ActivityIcon } from '../../icons/icons'

/**
 * Cognitive Report — the product's take-away deliverable.
 *
 * Everything on this page is composed from endpoints that already exist; it
 * adds no new inference of its own. That is the point: the other 20+ pages
 * each show one slice of the twin, and there was no single artefact a person
 * could read end-to-end, print, hand to someone, or archive. Personal weekly
 * review, a researcher's participant summary and an agency brief are all the
 * same document, so it's built once.
 *
 * Two rules it holds to, because they're the whole product's premise:
 *  - Every figure is sourced. Each section names the endpoint it came from,
 *    and nothing here is generated by a language model.
 *  - It refuses to sound more certain than the data allows — see Readiness
 *    below, which gates the report's own framing on data coverage.
 */

const pct = (v) => (typeof v === 'number' && Number.isFinite(v) ? Math.round(v * 100) : null)

const parseJSON = (v) => {
  if (v == null) return null
  if (typeof v === 'object') return v
  try { return JSON.parse(v) } catch { return null }
}

/**
 * Data-coverage thresholds.
 *
 * These are disclosure targets, not accuracy guarantees: each one is the point
 * past which that signal stops being dominated by noise from a handful of
 * events. They're stated in the UI rather than hidden, so a thin profile reads
 * as thin instead of quietly producing confident-looking output — the failure
 * mode that matters most for a product that profiles people.
 */
const READINESS = [
  { key: 'events', label: 'Behavioural events', target: 200, unlocks: 'Stable topic ranking and time-of-day patterns' },
  { key: 'topics', label: 'Tracked topics', target: 12, unlocks: 'Meaningful interest breadth and diversity scoring' },
  { key: 'evidence', label: 'Evidence items', target: 40, unlocks: 'Claims traceable to more than a few observations' },
  { key: 'inferences', label: 'Inferences drawn', target: 8, unlocks: 'Cross-checking one inference against another' },
  { key: 'snapshots', label: 'Identity snapshots', target: 5, unlocks: 'Change-over-time and drift detection' },
]

function SectionHeading({ title, source, right }) {
  return (
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 16, marginBottom: 18, flexWrap: 'wrap' }}>
      <div>
        <h3 style={{ fontSize: 17, fontWeight: 700, marginBottom: 4 }}>{title}</h3>
        {/* Provenance line — the reason a reader can trust any number above it. */}
        <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{source}</div>
      </div>
      {right}
    </div>
  )
}

function Empty({ children }) {
  return (
    <div style={{ padding: '22px 4px', color: 'var(--text-muted)', fontSize: 13.5, lineHeight: 1.6 }}>
      {children}
    </div>
  )
}

function Meter({ value, max = 1, color = 'var(--indigo-400)' }) {
  const w = Math.max(0, Math.min(100, (value / max) * 100))
  return (
    <div style={{ height: 6, borderRadius: 3, background: 'rgba(148,163,184,0.14)', overflow: 'hidden' }}>
      <div className="grow-w" style={{ height: '100%', width: `${w}%`, borderRadius: 3, background: color }} />
    </div>
  )
}

export default function ReportPage() {
  const [copied, setCopied] = useState(false)

  const { data: summary, loading: sumLoading } = useApi(() => api.getCognitiveSummary())
  const { data: identityRaw } = useApi(() => api.getCurrentIdentity())
  const { data: behaviors } = useApi(() => api.getBehaviorObjects(undefined, 50))
  const { data: inferences } = useApi(() => api.getInferences(undefined, 20))
  const { data: reflections } = useApi(() => api.getReflections(undefined, 3))
  const { data: guardian } = useApi(() => api.getGuardianReport())
  // The two audits. Each carries its OWN reliability gate (verdict_reliable,
  // measurable) independent of this page's coverage score, and each is
  // rendered only when its own gate allows — see the sections below.
  const { data: mirror } = useApi(() => api.getMirrorReport())
  const { data: provenance } = useApi(() => api.getProvenanceReport())

  const identity = identityRaw?.identity || identityRaw || null
  const sessions = guardian?.session_patterns || {}

  const dominantTopics = useMemo(() => {
    const parsed = parseJSON(identity?.dominant_topics)
    if (Array.isArray(parsed)) return parsed
    return Array.isArray(identity?.dominant_topics) ? identity.dominant_topics : []
  }, [identity])

  const interestGraph = useMemo(() => parseJSON(identity?.interest_graph) || {}, [identity])
  const domInterests = Array.isArray(interestGraph.dominant_interests) ? interestGraph.dominant_interests : []

  // Readiness is computed from the same counts the rest of the app reports —
  // no separate bookkeeping that could drift out of sync with reality.
  const readiness = useMemo(() => {
    const actuals = {
      events: sessions.total_events ?? 0,
      topics: summary?.behavior_object_count ?? 0,
      evidence: summary?.evidence_count ?? 0,
      inferences: summary?.inference_count ?? 0,
      snapshots: summary?.snapshot_count ?? 0,
    }
    const rows = READINESS.map(r => {
      const actual = actuals[r.key] ?? 0
      return { ...r, actual, ratio: Math.min(1, r.target > 0 ? actual / r.target : 0), met: actual >= r.target }
    })
    const score = rows.length ? rows.reduce((a, r) => a + r.ratio, 0) / rows.length : 0
    return { rows, score }
  }, [summary, sessions.total_events])

  // Framing follows the evidence rather than the other way round: the same
  // report is described differently depending on how much data stands behind it.
  const readinessBand = readiness.score >= 0.75
    ? { label: 'Well covered', variant: 'emerald', note: 'Enough data for the patterns below to be reasonably stable.' }
    : readiness.score >= 0.4
      ? { label: 'Partial coverage', variant: 'amber', note: 'Directionally useful, but individual figures can still move a lot with new data.' }
      : { label: 'Early / thin data', variant: 'danger', note: 'Treat everything below as provisional — there is not yet enough data to rely on it.' }

  // Peak hours come straight from Guardian's real hourly histogram.
  const peakHours = useMemo(() => {
    const dist = sessions.hourly_distribution || {}
    return Object.entries(dist)
      .map(([h, n]) => ({ hour: Number(h), count: Number(n) || 0 }))
      .filter(d => d.count > 0)
      .sort((a, b) => b.count - a.count)
      .slice(0, 3)
  }, [sessions.hourly_distribution])

  const topBehaviors = useMemo(
    () => (Array.isArray(behaviors) ? [...behaviors] : [])
      .sort((a, b) => (b.importance_score || 0) - (a.importance_score || 0))
      .slice(0, 8),
    [behaviors]
  )

  const sortedInferences = useMemo(
    () => (Array.isArray(inferences) ? [...inferences] : [])
      // Claims the user has denied sink to the bottom. They stay visible —
      // hiding a correction makes it invisible and irreversible — but the
      // report should lead with what still stands.
      .sort((a, b) => (Number(a.contested || false) - Number(b.contested || false))
        || (b.confidence || 0) - (a.confidence || 0)),
    [inferences]
  )
  const contestedCount = sortedInferences.filter(i => i.contested).length

  const latestReflection = Array.isArray(reflections) ? reflections[0] : null
  const generatedAt = new Date()

  const confidence = identity?.overall_confidence ?? summary?.current_identity?.overall_confidence
  const completeness = identity?.identity_completeness
  const version = identity?.identity_version ?? summary?.current_identity?.identity_version

  /** Plain-text digest — for pasting into a message, ticket or email. */
  const buildTextSummary = () => {
    const lines = [
      `AIMirror — Cognitive Report`,
      `Generated ${generatedAt.toLocaleString()}`,
      ``,
      `Data coverage: ${Math.round(readiness.score * 100)}% (${readinessBand.label}). ${readinessBand.note}`,
      `Identity: v${version ?? '?'}, confidence ${pct(confidence) ?? '--'}%, completeness ${pct(completeness) ?? '--'}%`,
      `Corpus: ${sessions.total_events ?? 0} events, ${summary?.behavior_object_count ?? 0} topics, ${summary?.evidence_count ?? 0} evidence, ${summary?.inference_count ?? 0} inferences`,
      ``,
      `Top interests: ${dominantTopics.slice(0, 5).join(', ') || 'none yet'}`,
      ``,
      `Inferences:`,
      ...(sortedInferences.length
        ? sortedInferences.slice(0, 5).map(i => `  - ${i.label} (${pct(i.confidence)}% confidence, ${i.rule_name})`)
        : ['  - none yet']),
      ``,
      `Wellbeing: risk ${guardian?.risk_level ?? 'unknown'}, late-night share ${pct(sessions.late_night_share) ?? 0}%`,
      ``,
      ...(mirror?.claims_total
        ? [
            `Platform profile audit (${mirror.claims_total} claims imported):`,
            mirror.verdict_reliable
              ? `  ${pct(mirror.summary?.supported_share) ?? '--'}% of ${mirror.summary?.testable_claims ?? 0} testable claims supported by behaviour`
              : `  Not enough data to judge this profile yet`,
            `  ${mirror.summary?.corroborated ?? 0} corroborated · ${mirror.summary?.unsupported ?? 0} unsupported · ${mirror.summary?.not_comparable ?? 0} not testable`,
            ``,
          ]
        : []),
      ...(provenance?.measurable
        ? [
            `Interest provenance:`,
            `  ${pct(provenance.summary?.fed_share_of_attention) ?? '--'}% of judged watching went to topics never sought out`,
            `  ${provenance.summary?.fed ?? 0} fed · ${provenance.summary?.mixed ?? 0} mixed · ${provenance.summary?.chosen ?? 0} chosen`,
            ``,
          ]
        : []),
      `All figures are computed deterministically from the account's own data. No language model was used to produce them.`,
    ]
    return lines.join('\n')
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(buildTextSummary())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      setCopied(false)
    }
  }

  /** Machine-readable version of exactly what's on screen — data portability
   *  for the report itself, not just the raw tables under Settings. */
  const handleDownloadJson = () => {
    const payload = {
      report: 'AIMirror Cognitive Report',
      generated_at: generatedAt.toISOString(),
      method: 'Composed from deterministic pipeline outputs. No language model contributed to any figure.',
      coverage: {
        score: Number(readiness.score.toFixed(3)),
        band: readinessBand.label,
        components: readiness.rows.map(r => ({ metric: r.key, actual: r.actual, target: r.target, met: r.met })),
      },
      identity: { version, overall_confidence: confidence, identity_completeness: completeness, dominant_topics: dominantTopics },
      corpus: {
        events: sessions.total_events ?? 0,
        behavior_objects: summary?.behavior_object_count ?? 0,
        evidence: summary?.evidence_count ?? 0,
        inferences: summary?.inference_count ?? 0,
        reflections: summary?.reflection_count ?? 0,
        snapshots: summary?.snapshot_count ?? 0,
        platform_breakdown: summary?.platform_breakdown ?? {},
      },
      attention: {
        total_watch_time_sec: sessions.total_watch_time_sec ?? 0,
        avg_watch_time_sec: sessions.avg_watch_time_sec ?? 0,
        late_night_share: sessions.late_night_share ?? 0,
        peak_hours: peakHours,
      },
      behaviors: topBehaviors.map(b => ({
        topic: b.topic, lifecycle_state: b.lifecycle_state,
        importance: b.importance_score, confidence: b.confidence_score,
        stability: b.stability_score, creators: (b.creators || []).length,
      })),
      inferences: sortedInferences.map(i => ({
        label: i.label, description: i.description, confidence: i.confidence,
        rule: i.rule_name, inferred_at: i.inferred_at,
      })),
      wellbeing: {
        risk_score: guardian?.risk_score, risk_level: guardian?.risk_level,
        risk_factors: guardian?.risk_factors ?? [],
        recommendations: guardian?.recommendations ?? [],
      },
      latest_reflection: latestReflection || null,
      // Both audits carry their own gate flags into the export, so a consumer
      // of this file cannot read a verdict without also reading whether the
      // verdict was considered reliable.
      platform_profile_audit: mirror?.claims_total
        ? {
            claims_total: mirror.claims_total,
            verdict_reliable: mirror.verdict_reliable,
            summary: mirror.summary,
            corroborated: mirror.corroborated,
            unsupported: mirror.unsupported,
            not_comparable: mirror.not_comparable,
            missed: mirror.missed,
            caveats: mirror.caveats,
          }
        : null,
      interest_provenance: provenance
        ? {
            measurable: provenance.measurable,
            summary: provenance.summary,
            topics: provenance.topics,
            caveats: provenance.caveats,
          }
        : null,
    }

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `aimirror-report-${generatedAt.toISOString().slice(0, 10)}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    // Revoking immediately can cancel the download in some browsers; one tick
    // after the click is enough for it to have been picked up.
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  const btn = {
    padding: '9px 16px', borderRadius: 10, fontSize: 13, fontWeight: 600,
    display: 'inline-flex', alignItems: 'center', gap: 7, cursor: 'pointer',
    border: '1px solid var(--border-strong)', background: 'var(--bg-surface)',
    color: 'var(--text-secondary)',
    backdropFilter: 'blur(12px)', WebkitBackdropFilter: 'blur(12px)',
  }

  return (
    <div className="report-root">
      {/* ------------------------------------------------------------ header */}
      <Reveal variant="depth">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', gap: 20, marginBottom: 30, flexWrap: 'wrap' }}>
          <div>
            <h1 className="gradient-text" style={{ fontSize: 34, fontWeight: 800, marginBottom: 6 }}>
              Cognitive Report
            </h1>
            <p style={{ color: 'var(--text-tertiary)', fontSize: 15 }}>
              One readable summary of your twin — sourced, printable, and safe to share.
            </p>
            <p style={{ color: 'var(--text-muted)', fontSize: 12, marginTop: 6, fontFamily: 'var(--font-mono)' }}>
              Generated {generatedAt.toLocaleString()}
            </p>
          </div>

          {/* Print goes through the browser's own dialog, which is also its
              "Save as PDF" — no extra dependency for a shareable file. */}
          <div className="report-actions" style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button className="btn-3d" style={btn} onClick={handleCopy}>
              {copied ? <CheckIcon /> : <CopyIcon />}
              {copied ? 'Copied' : 'Copy summary'}
            </button>
            <button className="btn-3d" style={btn} onClick={handleDownloadJson}>
              <DownloadIcon /> Download JSON
            </button>
            <button className="btn-3d btn-aurora" style={{ ...btn, border: 'none', color: 'white' }} onClick={() => window.print()}>
              Print / Save PDF
            </button>
          </div>
        </div>
      </Reveal>

      {/* -------------------------------------------------------- readiness */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading
            title="Data coverage"
            source="derived from /cognitive/summary + /guardian/report"
            right={<Badge variant={readinessBand.variant} dot>{readinessBand.label}</Badge>}
          />

          <div style={{ display: 'flex', alignItems: 'center', gap: 20, marginBottom: 20, flexWrap: 'wrap' }}>
            <div style={{ fontSize: 42, fontWeight: 800, lineHeight: 1, minWidth: 110 }} className="gradient-text">
              <CountUp value={`${Math.round(readiness.score * 100)}%`} />
            </div>
            <p style={{ flex: 1, minWidth: 260, fontSize: 13.5, color: 'var(--text-tertiary)', lineHeight: 1.65 }}>
              {readinessBand.note} Coverage is the mean of the five signals below, each capped at its target —
              it measures <em>how much is known</em>, not how accurate the twin is.
            </p>
          </div>

          <div style={{ display: 'grid', gap: 14 }}>
            {readiness.rows.map(r => (
              <div key={r.key}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 12, marginBottom: 6 }}>
                  <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--text-secondary)' }}>{r.label}</span>
                  <span className="tabular" style={{ fontSize: 12.5, color: r.met ? 'var(--emerald-400)' : 'var(--text-muted)' }}>
                    {r.actual} / {r.target} {r.met ? '✓' : ''}
                  </span>
                </div>
                <Meter value={r.ratio} color={r.met ? 'var(--emerald-400)' : 'var(--indigo-400)'} />
                {!r.met && (
                  <div style={{ fontSize: 11.5, color: 'var(--text-muted)', marginTop: 5 }}>
                    Unlocks at target: {r.unlocks}
                  </div>
                )}
              </div>
            ))}
          </div>
        </GlassCard>
      </Reveal>

      {/* --------------------------------------------------------- identity */}
      <Reveal variant="depth">
        <div className="stagger" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: 16, marginBottom: 26 }}>
          <StatCard label="Identity Confidence" value={confidence != null ? `${pct(confidence)}%` : '--'} icon={TargetIcon} accent="indigo" loading={sumLoading} />
          <StatCard label="Completeness" value={completeness != null ? `${pct(completeness)}%` : '--'} icon={LayersIcon} accent="violet" loading={sumLoading} />
          <StatCard label="Events Analysed" value={sessions.total_events ?? 0} icon={ActivityIcon} accent="cyan" loading={!guardian} />
          <StatCard label="Inferences" value={summary?.inference_count ?? 0} icon={BrainIcon} accent="emerald" loading={sumLoading} />
        </div>
      </Reveal>

      {/* -------------------------------------------------------- interests */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading title="What holds your attention" source="/identity/current · interest_graph" />
          {dominantTopics.length === 0 ? (
            <Empty>No dominant topics yet. Import activity or run a seed to populate this.</Empty>
          ) : (
            <div style={{ display: 'grid', gap: 12 }}>
              {dominantTopics.slice(0, 6).map((topic, i) => {
                const di = domInterests.find(d => d.topic === topic)
                const strength = typeof di?.strength === 'number' ? di.strength : null
                return (
                  <div key={`${topic}-${i}`}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginBottom: 6 }}>
                      <span style={{ fontSize: 13.5, color: 'var(--text-secondary)', fontWeight: 600 }}>{topic}</span>
                      <span className="tabular" style={{ fontSize: 12.5, color: 'var(--text-muted)' }}>
                        {strength != null ? `${pct(strength)}% strength` : 'rank ' + (i + 1)}
                      </span>
                    </div>
                    {/* Rank-based bar when the graph carries no strength, so the
                        row never implies a precision the data doesn't have. */}
                    <Meter
                      value={strength != null ? strength : (dominantTopics.length - i) / dominantTopics.length}
                      color={['var(--indigo-400)', 'var(--cyan-400)', 'var(--violet-400)', 'var(--pink-400)', 'var(--emerald-400)', 'var(--amber-400)'][i % 6]}
                    />
                  </div>
                )
              })}
            </div>
          )}
        </GlassCard>
      </Reveal>

      {/* --------------------------------------------------------- rhythm */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading title="Attention rhythm" source="/guardian/report · session_patterns" />
          {!sessions.total_events ? (
            <Empty>No session data yet.</Empty>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 18 }}>
              <div>
                <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 6 }}>Total watch time</div>
                <div className="tabular" style={{ fontSize: 22, fontWeight: 700 }}>
                  {Math.round((sessions.total_watch_time_sec || 0) / 60)} min
                </div>
              </div>
              <div>
                <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 6 }}>Average per item</div>
                <div className="tabular" style={{ fontSize: 22, fontWeight: 700 }}>
                  {Math.round(sessions.avg_watch_time_sec || 0)}s
                </div>
              </div>
              <div>
                <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 6 }}>Peak hours</div>
                <div style={{ fontSize: 15, fontWeight: 600, color: 'var(--text-secondary)' }}>
                  {peakHours.length
                    ? peakHours.map(p => `${String(p.hour).padStart(2, '0')}:00`).join(' · ')
                    : '—'}
                </div>
              </div>
              <div>
                <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 6 }}>Late-night share</div>
                <div className="tabular" style={{ fontSize: 22, fontWeight: 700, color: (sessions.late_night_share || 0) > 0.25 ? 'var(--amber-400)' : 'var(--emerald-400)' }}>
                  {pct(sessions.late_night_share) ?? 0}%
                </div>
              </div>
            </div>
          )}
        </GlassCard>
      </Reveal>

      {/* ------------------------------------------------------- behaviours */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading
            title="Tracked behaviour patterns"
            source="/reasoning/behavior-objects"
            right={<Badge variant="neutral">{topBehaviors.length} shown</Badge>}
          />
          {topBehaviors.length === 0 ? (
            <Empty>No behaviour objects have been consolidated yet.</Empty>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                <thead>
                  <tr style={{ textAlign: 'left', color: 'var(--text-muted)', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                    <th style={{ padding: '8px 10px 8px 0' }}>Topic</th>
                    <th style={{ padding: '8px 10px' }}>Stage</th>
                    <th style={{ padding: '8px 10px' }}>Importance</th>
                    <th style={{ padding: '8px 10px' }}>Stability</th>
                    <th style={{ padding: '8px 0 8px 10px' }}>Creators</th>
                  </tr>
                </thead>
                <tbody>
                  {topBehaviors.map(b => (
                    <tr key={b.unique_id} style={{ borderTop: '1px solid var(--border-subtle)' }}>
                      <td style={{ padding: '10px 10px 10px 0', color: 'var(--text-secondary)', fontWeight: 600 }}>{b.topic}</td>
                      <td style={{ padding: '10px' }}>
                        <Badge variant={b.lifecycle_state === 'growing' ? 'emerald' : b.lifecycle_state === 'declining' ? 'amber' : 'neutral'}>
                          {b.lifecycle_state || 'unknown'}
                        </Badge>
                      </td>
                      <td className="tabular" style={{ padding: '10px', color: 'var(--text-tertiary)' }}>{pct(b.importance_score) ?? '--'}%</td>
                      <td className="tabular" style={{ padding: '10px', color: 'var(--text-tertiary)' }}>{pct(b.stability_score) ?? '--'}%</td>
                      <td className="tabular" style={{ padding: '10px 0 10px 10px', color: 'var(--text-tertiary)' }}>{(b.creators || []).length}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </GlassCard>
      </Reveal>

      {/* -------------------------------------------------------- inferences */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading title="What the system concluded" source="/reasoning/inferences · each tagged with the rule that fired" />
          {contestedCount > 0 && (
            <p style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 12, lineHeight: 1.6 }}>
              {contestedCount} claim{contestedCount === 1 ? ' is' : 's are'} struck through:
              you marked {contestedCount === 1 ? 'it' : 'them'} wrong in the Accuracy Ledger,
              so the system no longer asserts {contestedCount === 1 ? 'it' : 'them'} in chat.
              Shown here rather than hidden, so the correction stays visible and you can take it back.
            </p>
          )}
          {sortedInferences.length === 0 ? (
            <Empty>No inferences yet — these appear once enough behaviour has accumulated for a rule to fire.</Empty>
          ) : (
            <div style={{ display: 'grid', gap: 12 }}>
              {sortedInferences.map(inf => (
                <div key={inf.inference_id} style={{
                  padding: '14px 16px', borderRadius: 12,
                  background: 'rgba(148,163,184,0.05)', border: '1px solid var(--border-subtle)',
                  opacity: inf.contested ? 0.62 : 1,
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginBottom: 6, flexWrap: 'wrap' }}>
                    <span style={{
                      fontSize: 14, fontWeight: 700, color: 'var(--text-primary)',
                      textDecoration: inf.contested ? 'line-through' : 'none',
                    }}>{inf.label}</span>
                    <span style={{ display: 'inline-flex', gap: 8, alignItems: 'center' }}>
                      {inf.contested && <Badge variant="rose">You marked this wrong</Badge>}
                      <Badge variant={(inf.confidence || 0) >= 0.75 ? 'emerald' : (inf.confidence || 0) >= 0.5 ? 'indigo' : 'amber'}>
                        {pct(inf.confidence)}% confidence
                      </Badge>
                      {/* Naming the rule is what makes this auditable rather
                          than an opaque assertion about a person. */}
                      <span style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{inf.rule_name}</span>
                    </span>
                  </div>
                  <p style={{ fontSize: 13, color: 'var(--text-tertiary)', lineHeight: 1.6 }}>{inf.description}</p>
                </div>
              ))}
            </div>
          )}
        </GlassCard>
      </Reveal>

      {/* --------------------------------------------------------- wellbeing */}
      <Reveal variant="depth">
        <GlassCard gradient style={{ marginBottom: 26 }}>
          <SectionHeading
            title="Wellbeing signal"
            source="/guardian/report"
            right={guardian && (
              <Badge variant={guardian.risk_level === 'low' ? 'emerald' : guardian.risk_level === 'high' ? 'danger' : 'amber'} dot>
                {guardian.risk_level} risk
              </Badge>
            )}
          />
          {!guardian ? (
            <Empty>Wellbeing report unavailable.</Empty>
          ) : (
            <div style={{ display: 'grid', gap: 14 }}>
              {(guardian.risk_factors || []).length > 0 && (
                <div>
                  <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 8 }}>Risk factors</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                    {guardian.risk_factors.map((f, i) => (
                      <Badge key={i} variant="amber">{typeof f === 'string' ? f : f.label || f.factor || 'factor'}</Badge>
                    ))}
                  </div>
                </div>
              )}
              {(guardian.recommendations || []).length > 0 && (
                <div>
                  <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 8 }}>Recommendations</div>
                  <ul style={{ margin: 0, paddingLeft: 18, display: 'grid', gap: 6 }}>
                    {guardian.recommendations.map((r, i) => (
                      <li key={i} style={{ fontSize: 13.5, color: 'var(--text-tertiary)', lineHeight: 1.6 }}>{r}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </GlassCard>
      </Reveal>

      {/* -------------------------------------------------------- reflection */}
      {latestReflection && (
        <Reveal variant="depth">
          <GlassCard gradient style={{ marginBottom: 26 }}>
            <SectionHeading
              title="Latest reflection"
              source="/reasoning/reflections"
              right={<Badge variant="neutral">{pct(latestReflection.confidence)}% confidence</Badge>}
            />
            <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.7, marginBottom: 14 }}>
              {latestReflection.summary}
            </p>
            {(latestReflection.key_insights || []).length > 0 && (
              <ul style={{ margin: 0, paddingLeft: 18, display: 'grid', gap: 6 }}>
                {latestReflection.key_insights.map((k, i) => (
                  <li key={i} style={{ fontSize: 13.5, color: 'var(--text-tertiary)', lineHeight: 1.6 }}>{k}</li>
                ))}
              </ul>
            )}
          </GlassCard>
        </Reveal>
      )}

      {/* ------------------------------------------------ platform audit */}
      {mirror?.claims_total > 0 && (
        <Reveal variant="depth">
          <GlassCard gradient style={{ marginBottom: 26 }}>
            <SectionHeading
              title="What the platform claims about you"
              source="/mirror/report - claims imported verbatim from your own export"
              right={
                <Badge variant={mirror.verdict_reliable ? 'indigo' : 'amber'} dot>
                  {mirror.verdict_reliable ? `${mirror.claims_total} claims` : 'provisional'}
                </Badge>
              }
            />

            {/* This section has its own reliability gate, independent of the
                coverage score above. A report can have enough data to describe
                someone and still not have enough to call a platform wrong. */}
            {!mirror.verdict_reliable ? (
              <Empty>
                {mirror.claims_total} claims were imported, but there is not yet enough
                behavioural data to test them. Judging a platform profile on this much
                history would produce confident-looking findings out of ignorance.
              </Empty>
            ) : (
              <>
                <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 14, color: (mirror.summary?.supported_share ?? 0) >= 0.6 ? 'var(--emerald-400)' : 'var(--amber-400)' }}>
                  {pct(mirror.summary?.supported_share)}% of {mirror.summary?.testable_claims} testable
                  claims are supported by your behaviour
                </div>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 16 }}>
                  <Badge variant="emerald">{mirror.summary?.corroborated} corroborated</Badge>
                  <Badge variant="amber">{mirror.summary?.unsupported} unsupported</Badge>
                  <Badge variant="neutral">{mirror.summary?.not_comparable} not testable</Badge>
                  <Badge variant="indigo">{mirror.summary?.missed} they miss</Badge>
                </div>

                {(mirror.unsupported || []).length > 0 && (
                  <div style={{ marginBottom: 14 }}>
                    <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 8 }}>
                      Targeted on, with no support in your history
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
                      {mirror.unsupported.slice(0, 14).map((c, i) => (
                        <Badge key={i} variant="amber">{c.label}</Badge>
                      ))}
                    </div>
                  </div>
                )}

                {(mirror.missed || []).length > 0 && (
                  <div>
                    <div style={{ fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text-muted)', marginBottom: 8 }}>
                      Well-evidenced interests they never target
                    </div>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
                      {mirror.missed.slice(0, 12).map((m, i) => (
                        <Badge key={i} variant="indigo">{m.topic} ({m.observations})</Badge>
                      ))}
                    </div>
                  </div>
                )}
              </>
            )}
          </GlassCard>
        </Reveal>
      )}

      {/* --------------------------------------------------- provenance */}
      {provenance?.topics?.length > 0 && (
        <Reveal variant="depth">
          <GlassCard gradient style={{ marginBottom: 26 }}>
            <SectionHeading
              title="Chosen or fed"
              source="/provenance/report - seeking weighed against exposure"
              right={
                <Badge variant={provenance.measurable ? 'indigo' : 'neutral'} dot>
                  {provenance.measurable ? 'measurable' : 'not measurable'}
                </Badge>
              }
            />

            {!provenance.measurable ? (
              <Empty>
                Agency cannot be measured for this account. Deciding whether an interest was
                chosen requires evidence of seeking - searches, likes, saves - and there is
                too little of it here. Reporting every topic as fed on that basis would be
                the wrong answer, not a cautious one.
              </Empty>
            ) : (
              <>
                <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 14, color: (provenance.summary?.fed_share_of_attention ?? 0) > 0.4 ? 'var(--rose-400)' : 'var(--emerald-400)' }}>
                  {pct(provenance.summary?.fed_share_of_attention)}% of judged watching went to
                  topics you never sought out
                </div>
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 16 }}>
                  <Badge variant="danger">{provenance.summary?.fed} fed</Badge>
                  <Badge variant="amber">{provenance.summary?.mixed} mixed</Badge>
                  <Badge variant="emerald">{provenance.summary?.chosen} chosen</Badge>
                  <Badge variant="neutral">{provenance.summary?.search_signals} search signals</Badge>
                </div>
                <div style={{ display: 'grid', gap: 8 }}>
                  {provenance.topics.filter(t => t.verdict !== 'unknown').slice(0, 10).map((t, i) => (
                    <div key={i} style={{ display: 'flex', justifyContent: 'space-between', gap: 12, fontSize: 13, flexWrap: 'wrap' }}>
                      <span style={{ fontWeight: 600, minWidth: 120 }}>{t.topic}</span>
                      <span className="tabular" style={{ color: 'var(--text-muted)', fontSize: 12, fontFamily: 'var(--font-mono)' }}>
                        {t.exposure} views - {t.searches} searches - {pct(t.agency)}% sought
                      </span>
                      <Badge variant={t.verdict === 'fed' ? 'danger' : t.verdict === 'chosen' ? 'emerald' : 'amber'}>
                        {t.verdict}
                      </Badge>
                    </div>
                  ))}
                </div>
              </>
            )}
          </GlassCard>
        </Reveal>
      )}

      {/* ------------------------------------------------------------ method */}
      <Reveal variant="depth">
        <GlassCard style={{ marginBottom: 12 }}>
          <SectionHeading title="Method" source="how to read this document" />
          <div style={{ fontSize: 13, color: 'var(--text-tertiary)', lineHeight: 1.75, display: 'grid', gap: 10 }}>
            <p>
              Every figure here is computed from this account's own recorded activity by the deterministic
              pipeline — the same code path the Pipeline page traces stage by stage. <strong>No language model
              contributed to any number, label or ranking on this page.</strong> Language models are used
              elsewhere in the product only to phrase answers the pipeline has already decided.
            </p>
            <p>
              Each section names the endpoint it reads, and every inference carries the rule that produced it,
              so any claim can be traced back to the observations behind it.
            </p>
            <p>
              Coverage is reported before conclusions on purpose. Behavioural profiles built from small samples
              look just as confident as ones built from large samples, so the report states how much data stands
              behind it and frames itself accordingly.
            </p>
            <p>
              The two audit sections carry their <strong>own</strong> reliability gates, which
              are stricter than this page's coverage score and independent of it. There is
              enough data to describe someone long before there is enough to call a platform
              wrong about them, and a section that cannot meet its own bar says so instead of
              reporting a number.
            </p>
            {summary?.platform_breakdown && Object.keys(summary.platform_breakdown).length > 0 && (
              <p style={{ color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 12 }}>
                Sources: {Object.entries(summary.platform_breakdown).map(([k, v]) => `${k} (${v})`).join(' · ')}
              </p>
            )}
          </div>
        </GlassCard>
      </Reveal>
    </div>
  )
}
